import {test} from 'node:test';import assert from 'node:assert/strict';
import {MISSIONS,CHAPTERS,PUZZLES,LESSONS,TODDLER,TOGETHER,fatherCycle,missionStory} from '../src/family/content.js';
import {puzzleSpec} from '../src/family/puzzles.js';
import {fresh,normalize,log,completions,nextMission,unlocked,mergeEvents,validEvent} from '../src/family/store.js';
test('v2 contains 200 uniquely named sequential missions, five stations each, ten chapters',()=>{assert.equal(MISSIONS.length,200);assert.equal(new Set(MISSIONS.map(m=>m.title)).size,200);assert.equal(MISSIONS.reduce((n,m)=>n+m.steps,0),1000);assert.equal(CHAPTERS.length,10);for(const c of CHAPTERS)assert.equal(c.titles.length,20);assert.equal(PUZZLES.length,20);});
test('every puzzle in every mission has a valid nontrivial configuration',()=>{for(const m of MISSIONS)for(const type of PUZZLES){const s=puzzleSpec(type,m);assert.ok(s.question.length>10);assert.ok(s.hint);if(s.options&&['choice','geography'].includes(s.kind)){assert.equal(new Set(s.options).size,s.options.length,`${type}/${m.id}`);assert.ok(s.correct>=0&&s.correct<s.options.length);}if(s.kind==='route'){assert.equal(s.route[0],s.start);assert.equal(s.route.at(-1),s.goal);for(let i=1;i<s.route.length;i++){let a=s.route[i-1],b=s.route[i];assert.equal(Math.abs(a%5-b%5)+Math.abs(Math.floor(a/5)-Math.floor(b/5)),1);assert.ok(s.open.includes(b));}}if(s.kind==='pixels'){assert.equal(s.target.length,9);assert.ok(s.target.some(x=>x));}if(s.kind==='market'){assert.equal(s.prices[0]+s.prices[2],s.target);}if(s.kind==='order')assert.deepEqual([...s.items].sort(),[...s.answer].sort());}});
test('early years and parent curricula include genuine activities and differentiated family roles',()=>{assert.equal(TODDLER.length,12);assert.equal(LESSONS.length,15);assert.equal(TOGETHER.length,6);for(const t of TOGETHER){assert.ok(t.big&&t.small&&t.adult&&t.reflect);}for(const l of LESSONS){assert.equal(l.choices.length,3);assert.ok(l.say&&l.why&&l.practice);}});
test('father schedule honors ten away days, five home days, and repeats at day 16',()=>{for(let i=0;i<30;i++){const date=new Date(Date.UTC(2026,8,1+i)).toISOString().slice(0,10);const r=fatherCycle('2026-09-01',date);assert.equal(r.day,i%15+1);assert.equal(r.away,i%15<10);}assert.equal(fatherCycle('2026-10-01','2026-09-01').future,true);});
test('event merge is idempotent; completion and unlock are derived from recorded progress',()=>{const s=fresh();assert.equal(nextMission(s).id,1);assert.equal(unlocked(s,2),false);const e=log(s,'explorer','mission',1,{interest:'قصه'});assert.equal(validEvent(e),true);assert.equal(nextMission(s).id,2);assert.equal(unlocked(s,2),true);assert.equal(completions(s,'explorer','mission').size,1);assert.equal(mergeEvents(s.events,s.events).length,1);assert.equal(normalize({events:[e,{id:'bad'}]}).events.length,1);});
test('preferences normalize independently without importing tokens or executable artwork',()=>{const n=normalize({role:'invalid',voices:{mother:'second',father:'invalid'},token:'secret',art:['javascript:alert(1)'],favorites:[0,2,-1,99]});assert.equal(n.voices.mother,'second');assert.equal(n.voices.father,'first');assert.equal(n.token,undefined);assert.deepEqual(n.art,[]);assert.deepEqual(n.favorites,[0,2]);});

test('all mission episodes have unique text and a valid consequence-based answer',()=>{const all=MISSIONS.map(missionStory);assert.equal(new Set(all.map(s=>s.text)).size,200);for(const s of all){assert.equal(s.choices.length,3);assert.ok(s.answer>=0&&s.answer<3);assert.ok(s.why);}});
