import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createFamilyServer} from '../server/index.js';
test('private sync: auth, isolation, deduplication, validation, encryption, consent endpoint and deletion',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bagh-test-'));const server=createFamilyServer({directory:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/api/`;
 const call=async(route,body,token='',method=body?'POST':'GET')=>{const response=await fetch(base+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});return {status:response.status,data:await response.json()};};
 try{assert.equal((await call('events')).status,401);assert.equal((await call('register',{username:'a',password:'short'})).status,400);const a=await call('register',{username:'parentA',password:'not-a-real-password-123'}),b=await call('register',{username:'parentB',password:'another-test-password-456'});assert.equal(a.status,201);assert.equal(b.status,201);const token=a.data.token;assert.equal((await call('login',{username:'parentA',password:'wrong-test-password'})).status,401);
 const event={id:'test-event-1',role:'explorer',kind:'mission',subject:'1',at:Date.now(),data:{interest:'PRIVATE_TEST_SENTENCE'}};
 assert.equal((await call('events',{events:[event]},token)).status,200);await call('events',{events:[event]},token);assert.equal((await call('events',null,token)).data.events.length,1);assert.equal((await call('events',null,b.data.token)).data.events.length,0);assert.equal((await call('events',{events:[{id:'bad'}]},token)).status,400);
 const raw=fs.readdirSync(dir).filter(f=>f.startsWith('family.sqlite')).map(f=>fs.readFileSync(path.join(dir,f))).reduce((a,b)=>Buffer.concat([a,b]),Buffer.alloc(0));assert.equal(raw.includes(Buffer.from('PRIVATE_TEST_SENTENCE')),false);assert.equal(raw.includes(Buffer.from('not-a-real-password-123')),false);
 const forbidden=await fetch(base+'health',{headers:{Origin:'https://untrusted.example'}});assert.equal(forbidden.status,403);const accepted=await fetch(base+'health',{headers:{Origin:'https://app.littlestar.local'}});assert.equal(accepted.headers.get('access-control-allow-origin'),'https://app.littlestar.local');
 assert.equal((await call('account',{password:'wrong-password'},token,'DELETE')).status,403);assert.equal((await call('account',{password:'not-a-real-password-123'},token,'DELETE')).status,200);assert.equal((await call('events',null,token)).status,401);assert.equal((await call('login',{username:'parentA',password:'not-a-real-password-123'})).status,401);
 }finally{await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}
});
