export const fa=v=>String(v).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
export function shuffle(a,seed=1){a=[...a];let x=seed+11;for(let i=a.length-1;i>0;i--){x=(x*1664525+1013904223)>>>0;let j=x%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
const steps=['پرسش','حدس','آزمایش','نتیجه'];
export function puzzleSpec(type,m){const id=m.id,L=m.level,n=3+id%5;
 const choose=(question,options,correct,hint,extra={})=>{const list=shuffle(options,id);return {kind:'choice',question,options:list,correct:list.indexOf(correct),hint,...extra};};
 if(['river','maze'].includes(type)){const paths=[[20,15,16,11,6,7,8,3,4],[20,21,16,17,12,7,2,3,4],[20,15,10,11,12,13,8,9,4],[20,21,22,17,18,13,14,9,4]];const route=paths[id%4];return {kind:'route',question:type==='river'?'آب را از چشمه تا درخت برسان. هر بار یک خانهٔ همسایه را لمس کن.':'راه کاوشگر تا کتابخانه را پیدا کن. حرکت مورب نداریم.',route,start:20,goal:4,open:[...new Set([...route,...[0,5,19,24,23].filter(x=>!route.includes(x))])],hint:'از خانهٔ روشن شروع کن. خانهٔ بعد باید از کنار به مسیر وصل باشد؛ نه از گوشه.'};}
 if(type==='balance')return {kind:'balance',question:'با وزنه‌ها دو کفه را برابر کن. می‌توانی وزنه‌ای را کم یا زیاد کنی.',target:10+id%16,weights:[1,3,5],hint:'اول وزنهٔ بزرگ‌تر را امتحان کن، بعد اختلاف باقی‌مانده را با ۳ و ۱ بساز.'};
 if(type==='market'){let b=id%5+2,prices=[b,b+2,b+5,b+9];return {kind:'market',question:'دقیقاً دو وسیله انتخاب کن؛ جمع قیمتشان باید برابر بودجه باشد.',prices,target:prices[0]+prices[2],names:['دفتر','مداد','کتاب','کیف'],hint:'هم تعداد وسیله‌ها مهم است، هم جمع قیمت. اگر جمع زیاد شد یک انتخاب را بردار.'};}
 if(['mirror','mosaic'].includes(type)){const bits=Array.from({length:9},(_,i)=>(i*7+id)%4<2?1:0);const target=Array.from({length:9},(_,i)=>type==='mirror'?bits[Math.floor(i/3)*3+2-i%3]:bits[(2-i%3)*3+Math.floor(i/3)]);return {kind:'pixels',source:bits,target,question:type==='mirror'?'نقش سمت راست را مثل آینهٔ نقش نمونه بساز؛ چپ و راست جابه‌جا می‌شوند.':'نقش نمونه را یک‌چهارم دور، در جهت ساعت بچرخان و روی کاشی‌ها بساز.',hint:type==='mirror'?'خانهٔ بالا چپِ نمونه به بالا راستِ پاسخ می‌رود.':'خانهٔ بالا چپِ نمونه به بالا راست می‌رود؛ خانهٔ پایین چپ به بالا چپ.'};}
 if(type==='code'){let a=id%5+1;return {kind:'code',target:[a,a+2,a+1],question:`رمز سه‌رقمی را پیدا کن: رقم اول ${fa(a)} است. رقم دوم دو تا بیشتر از اول است. رقم سوم یکی کمتر از دوم است.`,hint:'از چپ به راست شروع کن. با دکمه‌های هر ستون، رقم را تنظیم کن.'};}
 if(type==='memory'){const pairs=L<3?4:6;return {kind:'memory',deck:shuffle([...Array(pairs).keys(),...Array(pairs).keys()],id),question:'دو نشانهٔ یکسان را پیدا کن. پیش از انتخاب بعدی، جای تصویرها را به خاطر بسپار.',hint:'برای هر تصویر یک نشانی در ذهن بساز؛ مثلاً «درخت بالای سمت راست».'};}
 if(type==='rhythm')return {kind:'rhythm',pattern:Array.from({length:Math.min(5,L+2)},(_,i)=>(id+i*3+Math.floor(i/2))%3),question:'به ترتیب آواها گوش کن، بعد همان ترتیب را با سه کلید بساز.',hint:'اگر شنیدن راحت نیست، راهنمای دیداری را روشن کن؛ هر رنگ یک آواست.'};
 if(type==='sort'){const answer=[n,n+3,n+7,n+12];return {kind:'order',answer:answer.map(String),items:shuffle(answer.map(String),id),question:'عددها را از کوچک به بزرگ در جایگاه‌ها بگذار.',hint:'هر بار کوچک‌ترین عددِ باقی‌مانده را انتخاب کن.',numeric:true};}
 if(type==='words'){const answer=[['مهربانی','از','شنیدن','شروع','می‌شود'],['من','می‌توانم','دوباره','تلاش','کنم'],['آب','را','بیهوده','هدر','ندهیم']][id%3];return {kind:'order',answer,items:shuffle(answer,id),question:'واژه‌ها را به ترتیب لمس کن تا این جمله ساخته شود: «'+answer.join(' ')+'»',hint:'با واژهٔ آغاز جمله شروع کن. می‌توانی ترتیب را پاک کنی و دوباره بسازی.'};}
 if(['planning','timeline'].includes(type)){const answer=type==='planning'?['شناخت مسئله','کشیدن طرح','ساخت نمونه','آزمایش و بهبود']:[['کاشت بذر','جوانه‌زدن','رشد گیاه','رسیدن میوه'],steps,['نامهٔ کاغذی','تلگراف','تلفن','تماس تصویری']][id%3];return {kind:'order',answer,items:shuffle(answer,id),question:type==='planning'?'برای ساخت یک پل، قدم‌ها را به ترتیب منطقی بچین.':'این مسیر را از مرحلهٔ زودتر به مرحلهٔ بعدی مرتب کن.',hint:'فکر کن کدام کار باید قبل از کار بعدی اتفاق افتاده باشد.'};}
 if(type==='nutrition')return {kind:'multi',question:'برای این سبد، از هر گروه خواسته‌شده یک مورد بردار: میوه، غله و سبزی.',options:['سیب · میوه','نان · غله','هویج · سبزی','آبنبات · شیرینی'],correct:[0,1,2],hint:'سه گروه در سؤال آمده. هدف تنوع غذایی است، نه «خوب یا بد» نامیدن آدم‌ها و خوراکی‌ها.'};
 if(type==='geography'){const facts=[['دریای خزر','شمال ایران'],['خلیج فارس','جنوب ایران'],['زاگرس','بخش غربی ایران'],['دشت کویر','بخش مرکزی ایران']];const target=id%4;return {...choose(`کدام نام با «${facts[target][1]}» ارتباط دارد؟`,facts.map(f=>f[0]),facts[target][0],'جهت‌ها را با هم مرور کن: شمال بالا و جنوب پایینِ این نقشهٔ نمادین است.'),kind:'geography',facts};}
 if(type==='cipher'){const words=['کار','بار','نان','بان'];const word=words[id%4],map={'ک':'۱','ا':'۲','ر':'۳','ب':'۴','ن':'۵'};return choose('با راهنمای رمز، واژه را پیدا کن.',words,word,'هر علامت را جداگانه به حرف تبدیل کن، بعد حروف را به ترتیب بخوان.',{cipher:[...word].map(c=>map[c]).join(' · '),legend:'۱ = ک     ۲ = ا     ۳ = ر     ۴ = ب     ۵ = ن'});}
 if(type==='sequence'){let step=L+1,answer=id%2?n+step*4:n*16;const nums=id%2?[n,n+step,n+step*2,n+step*3]:[n,n*2,n*4,n*8];return choose('عدد بعدی الگو چیست؟',[String(answer),String(answer+step+3),String(answer-1),String(answer+2)],String(answer),id%2?`هر بار ${fa(step)} تا اضافه کن.`:'هر عدد دو برابر عدد قبلی است.',{numeric:true,sequence:nums});}
 if(type==='fractions'){const denominator=8,numerator=id%6+1;return choose('چه کسری از دایره رنگ شده است؟',[`${numerator}/8`,`${numerator+1}/8`,`${numerator}/4`,`${8-numerator}/9`],`${numerator}/8`,'تعداد قسمت‌های رنگی صورت کسر است؛ تعداد همهٔ قسمت‌های برابر، مخرج کسر.',{fraction:[numerator,denominator]});}
 if(type==='logic'){let target=id%3;const list=['مثلث سبز','مربع بنفش','دایرهٔ نارنجی'];return choose(`نشانهٔ ما ${['سه ضلع دارد و رنگش سبز است','چهار ضلع دارد و رنگش بنفش است','گوشه ندارد و نارنجی است'][target]}. کدام است؟`,list,list[target],'هم شکل و هم رنگ باید با دو شرط سازگار باشند.',{shapes:true});}
 if(type==='detective'){const cases=[['برگ‌ها افتاده‌اند. خاک خشک است. دیروز آبیاری نشده.','اول رطوبت خاک و نیاز گیاه را بررسی کنیم'],['دوستت امروز ساکت است. دیشب کم خوابیده. هنوز از او نپرسیده‌ای.','با احترام بپرسیم چه چیزی لازم دارد'],['پل با کتاب سنگین خم شد. با کاغذ سبک خم نشد.','اثر وزن را با یک آزمایش امن مقایسه کنیم']];let q=cases[id%3];return choose(q[0]+' بهترین گام بعدی؟',[q[1],'بدون بررسی، یک نتیجهٔ قطعی بگیریم','همه چیز را رها کنیم'],q[1],'نشانه‌ها به ما جهت می‌دهند؛ برای نتیجهٔ مطمئن‌تر هنوز باید بررسی کنیم.');}
 throw Error('Unknown puzzle '+type);
}
export function mountPuzzle(root,type,mission,{onSolve,onHint,sound=true}){
 const spec=puzzleSpec(type,mission);let cleanups=[],solved=false;const $=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];
 root.innerHTML=`<p class="game-question">${spec.question}</p><div class="game-board"></div><div class="game-feedback" role="status"></div><div class="game-tools"><button class="f-btn light" id="hint-button">یک سرنخ می‌خواهم</button><span>بدون عجله؛ فرصت دوباره داری.</span></div>`;
 const board=$('.game-board');let attempts=0;
 const good=()=>{if(solved)return;solved=true;all('button').forEach(b=>b.disabled=true);$('.game-feedback').className='game-feedback positive';$('.game-feedback').textContent='پیدایش کردی! روش و تلاشت به نتیجه رسید.';onSolve({attempts});};
 const wrong=()=>{attempts++;$('.game-feedback').className='game-feedback rethink';$('.game-feedback').textContent='هنوز همهٔ شرط‌ها جور نشده. یک انتخاب را عوض کن یا از سرنخ کمک بگیر.';};
 $('#hint-button').onclick=()=>{onHint();$('.game-feedback').className='game-feedback rethink';$('.game-feedback').textContent=spec.hint;};
 if(['choice','geography'].includes(spec.kind)){
 let illustration=spec.sequence?`<div class="number-train" dir="ltr">${spec.sequence.map(v=>`<span>${fa(v)}</span>`).join('')}<span>؟</span></div>`:spec.cipher?`<div class="cipher-code" dir="rtl">${spec.cipher}</div><p class="legend">${spec.legend}</p>`:spec.fraction?`<div class="fraction-disc" style="--amount:${spec.fraction[0]/8*360}deg"></div><p class="legend">۸ قسمت برابر؛ ${fa(spec.fraction[0])} قسمت رنگی</p>`:spec.kind==='geography'?'<div class="geography-art"><span>شمال · خزر</span><b>ایران</b><span>جنوب · خلیج فارس</span><small>نقشهٔ نمادین؛ نه مقیاس جغرافیایی</small></div>':'';
 board.innerHTML=illustration+`<div class="answer-options">${spec.options.map((o,i)=>`<button data-choice="${i}" ${spec.numeric?'dir="ltr"':''}>${fa(o)}</button>`).join('')}</div>`;
 all('[data-choice]').forEach(b=>b.onclick=()=>{if(+b.dataset.choice===spec.correct){b.classList.add('right');good();}else{b.classList.add('retry-answer');wrong();}});
 }
 if(spec.kind==='route'){let route=[spec.start];board.innerHTML=`<div class="route-grid ${type==='river'?'river-grid':''}" dir="ltr">${Array.from({length:25},(_,i)=>`<button aria-label="خانه ${i+1}" data-cell="${i}" class="${spec.open.includes(i)?'open':'wall'} ${i===spec.start?'visited current':''}" ${!spec.open.includes(i)?'disabled':''}>${i===spec.start?'●':i===spec.goal?'★':spec.open.includes(i)?'·':'▰'}</button>`).join('')}</div><button class="f-btn light reset-route">از اول مسیر بکش</button>`;
 const update=()=>all('[data-cell]').forEach(b=>{b.classList.toggle('visited',route.includes(+b.dataset.cell));b.classList.toggle('current',+b.dataset.cell===route[route.length-1]);});
 all('[data-cell]').forEach(b=>b.onclick=()=>{let cell=+b.dataset.cell,last=route[route.length-1];if(Math.abs(Math.floor(last/5)-Math.floor(cell/5))+Math.abs(last%5-cell%5)!==1){wrong();return;}if(route.includes(cell))route=route.slice(0,route.indexOf(cell)+1);else route.push(cell);update();if(cell===spec.goal)good();});$('.reset-route').onclick=()=>{route=[spec.start];update();};
 }
 if(spec.kind==='balance'){let counts=[0,0,0];board.innerHTML=`<div class="scale-art"><div><strong>${fa(spec.target)}</strong><span>وزن هدف</span></div><b>⚖</b><div><strong id="weight-total">۰</strong><span>وزنه‌های تو</span></div></div><div class="weights">${spec.weights.map((w,i)=>`<div><b>${fa(w)} واحد</b><button data-weight-add="${i}" aria-label="افزودن وزنه ${w}">+</button><span id="weight-${i}">۰</span><button data-weight-remove="${i}" aria-label="برداشتن وزنه ${w}">−</button></div>`).join('')}</div><button class="f-btn" id="check-balance">ترازو را بسنج</button>`;const update=()=>{spec.weights.forEach((w,i)=>$('#weight-'+i).textContent=fa(counts[i]));$('#weight-total').textContent=fa(counts.reduce((s,n,i)=>s+n*spec.weights[i],0));};all('[data-weight-add]').forEach(b=>b.onclick=()=>{counts[+b.dataset.weightAdd]=Math.min(30,counts[+b.dataset.weightAdd]+1);update();});all('[data-weight-remove]').forEach(b=>b.onclick=()=>{counts[+b.dataset.weightRemove]=Math.max(0,counts[+b.dataset.weightRemove]-1);update();});$('#check-balance').onclick=()=>counts.reduce((s,n,i)=>s+n*spec.weights[i],0)===spec.target?good():wrong();}
 if(spec.kind==='market'||spec.kind==='multi'){let selected=new Set();const options=spec.kind==='market'?spec.names:spec.options;board.innerHTML=(spec.kind==='market'?`<div class="budget">بودجهٔ تو <b>${fa(spec.target)} سکه</b> · خرج‌شده: <b id="spent">۰</b></div>`:'')+`<div class="answer-options">${options.map((o,i)=>`<button data-item="${i}" aria-pressed="false">${o}${spec.prices?`<small>${fa(spec.prices[i])} سکه</small>`:''}</button>`).join('')}</div><button class="f-btn" id="check-items">سبدم را بررسی کن</button>`;all('[data-item]').forEach(b=>b.onclick=()=>{let i=+b.dataset.item;if(selected.has(i))selected.delete(i);else selected.add(i);b.classList.toggle('picked',selected.has(i));b.setAttribute('aria-pressed',selected.has(i));if($('#spent'))$('#spent').textContent=fa([...selected].reduce((n,i)=>n+spec.prices[i],0));});$('#check-items').onclick=()=>{const correct=spec.kind==='market'?selected.size===2&&[...selected].reduce((n,i)=>n+spec.prices[i],0)===spec.target:selected.size===spec.correct.length&&spec.correct.every(i=>selected.has(i));correct?good():wrong();};}
 if(spec.kind==='pixels'){let bits=Array(9).fill(0);board.innerHTML=`<div class="pixel-pair" dir="ltr"><div><p>نقش نمونه</p><div class="pixel-grid">${spec.source.map(b=>`<span class="${b?'filled':''}"></span>`).join('')}</div></div><b>→</b><div><p>نقش تو</p><div class="pixel-grid">${bits.map((b,i)=>`<button data-pixel="${i}" aria-label="کاشی ${i+1}" aria-pressed="false"></button>`).join('')}</div></div></div><button class="f-btn" id="check-pixels">نقشم را بررسی کن</button>`;all('[data-pixel]').forEach(b=>b.onclick=()=>{let i=+b.dataset.pixel;bits[i]=1-bits[i];b.classList.toggle('filled',!!bits[i]);b.setAttribute('aria-pressed',!!bits[i]);});$('#check-pixels').onclick=()=>bits.every((v,i)=>v===spec.target[i])?good():wrong();}
 if(spec.kind==='code'){let digits=[0,0,0];board.innerHTML=`<div class="code-lock" dir="ltr">${digits.map((n,i)=>`<div><button data-digit="${i}" aria-label="افزایش رقم ${i+1}">+</button><b id="digit-${i}">۰</b><button data-down="${i}" aria-label="کاهش رقم ${i+1}">−</button></div>`).join('')}</div><button class="f-btn" id="check-code">قفل را امتحان کن</button>`;const change=(i,d)=>{digits[i]=(digits[i]+d+10)%10;$('#digit-'+i).textContent=fa(digits[i]);};all('[data-digit]').forEach(b=>b.onclick=()=>change(+b.dataset.digit,1));all('[data-down]').forEach(b=>b.onclick=()=>change(+b.dataset.down,-1));$('#check-code').onclick=()=>digits.every((v,i)=>v===spec.target[i])?good():wrong();}
 if(spec.kind==='order'){let chosen=[];board.innerHTML=`<div class="order-slots" ${spec.numeric?'dir="ltr"':''}>${spec.answer.map(()=>'<span>…</span>').join('')}</div><div class="word-options">${spec.items.map((v,i)=>`<button data-order="${i}">${fa(v)}</button>`).join('')}</div><div class="game-bottom-buttons"><button class="f-btn light" id="order-reset">دوباره بچین</button><button class="f-btn" id="check-order">ترتیب را بررسی کن</button></div>`;all('[data-order]').forEach(b=>b.onclick=()=>{chosen.push(spec.items[+b.dataset.order]);b.disabled=true;$('.order-slots').children[chosen.length-1].textContent=fa(chosen[chosen.length-1]);});$('#order-reset').onclick=()=>{chosen=[];all('[data-order]').forEach(b=>b.disabled=false);[...$('.order-slots').children].forEach(s=>s.textContent='…');};$('#check-order').onclick=()=>chosen.length===spec.answer.length&&chosen.every((v,i)=>v===spec.answer[i])?good():wrong();}
 if(spec.kind==='memory'){let opened=[],matched=new Set(),busy=false;const symbols=['🌳','🦋','🌷','🌍','🎨','📖'];board.innerHTML=`<div class="memory-board">${spec.deck.map((_,i)=>`<button data-memory="${i}" aria-label="کارت ${i+1}">✦</button>`).join('')}</div><p id="pairs-count" class="muted-text">۰ جفت</p>`;all('[data-memory]').forEach(b=>b.onclick=()=>{const i=+b.dataset.memory;if(busy||opened.includes(i)||matched.has(i))return;b.textContent=symbols[spec.deck[i]];b.classList.add('flipped');opened.push(i);if(opened.length<2)return;if(spec.deck[opened[0]]===spec.deck[opened[1]]){opened.forEach(n=>{matched.add(n);$(`[data-memory="${n}"]`).classList.add('matched');});opened=[];$('#pairs-count').textContent=fa(matched.size/2)+' جفت';if(matched.size===spec.deck.length)good();}else{busy=true;const timer=setTimeout(()=>{opened.forEach(n=>{const c=$(`[data-memory="${n}"]`);if(c){c.textContent='✦';c.classList.remove('flipped');}});opened=[];busy=false;},900);cleanups.push(()=>clearTimeout(timer));}});}
 if(spec.kind==='rhythm'){let sequence=[],audioContext=null,playing=false;board.innerHTML=`<button class="listen-orb" id="hear-pattern">▶</button><p class="muted-text">پخش آواها با صدای ملایم</p><div class="rhythm-keys">${['بم','میانه','زیر'].map((s,i)=>`<button data-note="${i}">${s}</button>`).join('')}</div><div class="rhythm-output" id="rhythm-output">${spec.pattern.map(()=>'<i></i>').join('')}</div><button class="f-btn light" id="show-pattern">راهنمای دیداری</button><p class="legend" id="rhythm-hint"></p><button class="f-btn light" id="rhythm-reset">از نو بنواز</button>`;
 const tone=i=>{if(!sound)return;try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.frequency.value=[330,490,660][i];gain.gain.setValueAtTime(.09,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.3);osc.connect(gain);gain.connect(audioContext.destination);osc.start();osc.stop(audioContext.currentTime+.3);}catch{$('#rhythm-hint').textContent='صدا در دسترس نیست؛ راهنمای دیداری را ببین.';}};
 $('#hear-pattern').onclick=()=>{if(playing)return;if(!sound){$('#rhythm-hint').textContent='صدا خاموش است؛ راهنمای دیداری را ببین.';return;}playing=true;spec.pattern.forEach((n,i)=>{let timer=setTimeout(()=>tone(n),i*550);cleanups.push(()=>clearTimeout(timer));});let t=setTimeout(()=>playing=false,spec.pattern.length*550);cleanups.push(()=>clearTimeout(t));};
 $('#show-pattern').onclick=()=>$('#rhythm-hint').textContent=spec.pattern.map(i=>['بم','میانه','زیر'][i]).join(' ← ');
 all('[data-note]').forEach(b=>b.onclick=()=>{if(playing)return;let i=+b.dataset.note;tone(i);sequence.push(i);if(i!==spec.pattern[sequence.length-1]){wrong();sequence=[];[...$('#rhythm-output').children].forEach(c=>c.className='');return;}$('#rhythm-output').children[sequence.length-1].className='note-'+i;if(sequence.length===spec.pattern.length)good();});$('#rhythm-reset').onclick=()=>{sequence=[];[...$('#rhythm-output').children].forEach(c=>c.className='');};cleanups.push(()=>audioContext?.close());
 }
 return ()=>cleanups.forEach(fn=>fn());
}
