import {MISSIONS,ROLES} from './content.js';
const KEY='hamrah-family-v2';
export const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export const fresh=()=>({version:2,role:'explorer',names:{explorer:'کاوشگر',toddler:'جوانه'},voices:{explorer:'first',toddler:'first',mother:'first',father:'first'},events:[],drafts:{},energy:'normal',cycleStart:today(),limit:20,activeSeconds:0,sound:true,favorites:[],art:[],serverUrl:''});
export function normalize(raw){const s=fresh();if(!raw||typeof raw!=='object')return s;s.role=ROLES.some(r=>r.id===raw.role)?raw.role:s.role;for(const r of ROLES){s.voices[r.id]=raw.voices?.[r.id]==='second'?'second':'first';}for(const role of ['explorer','toddler'])if(typeof raw.names?.[role]==='string')s.names[role]=raw.names[role].slice(0,24);s.events=Array.isArray(raw.events)?raw.events.filter(validEvent).slice(-10000):[];s.drafts=raw.drafts&&typeof raw.drafts==='object'&&!Array.isArray(raw.drafts)?raw.drafts:{};s.energy=['low','normal','high'].includes(raw.energy)?raw.energy:'normal';s.cycleStart=/^\d{4}-\d{2}-\d{2}$/.test(raw.cycleStart)?raw.cycleStart:today();s.limit=[15,20,30].includes(raw.limit)?raw.limit:20;s.activeSeconds=Number.isFinite(raw.activeSeconds)?Math.max(0,raw.activeSeconds):0;s.sound=raw.sound!==false;s.favorites=Array.isArray(raw.favorites)?raw.favorites.filter(n=>Number.isInteger(n)&&n>=0&&n<10):[];s.art=Array.isArray(raw.art)?raw.art.filter(a=>typeof a==='string'&&/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(a)).slice(-6):[];s.serverUrl=typeof raw.serverUrl==='string'?raw.serverUrl.slice(0,200):'';return s;}
export function validEvent(e){return e&&typeof e.id==='string'&&e.id.length<=100&&ROLES.some(r=>r.id===e.role)&&['mission','toddler','lesson','routine','together','reflection'].includes(e.kind)&&typeof e.subject==='string'&&e.subject.length<=80&&Number.isFinite(e.at)&&e.at>0&&e.at<Date.now()+86400000&&typeof e.data==='object'&&e.data!==null&&JSON.stringify(e.data).length<=4000;}
export function load(){try{return normalize(JSON.parse(localStorage.getItem(KEY)));}catch{return fresh();}}
export function persist(state){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{return false;}}
export function log(state,role,kind,subject,data={}){const e={id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`,role,kind,subject:String(subject),at:Date.now(),data};state.events.push(e);return e;}
export const completions=(state,role,kind)=>new Set(state.events.filter(e=>e.role===role&&e.kind===kind).map(e=>e.subject));
export function nextMission(state){const done=completions(state,'explorer','mission');return MISSIONS.find(m=>!done.has(String(m.id)))||MISSIONS[199];}
export function unlocked(state,id){const done=completions(state,'explorer','mission');return id===1||done.has(String(id-1))||done.has(String(id));}
export function mergeEvents(a,b){return [...new Map([...a,...b].filter(validEvent).map(e=>[e.id,e])).values()].sort((x,y)=>x.at-y.at).slice(-10000);}
export function recommendations(state){const done=state.events.filter(e=>e.role==='explorer'&&e.kind==='mission');const last=done.slice(-3);const recommendations=[];if(!done.length)recommendations.push({title:'اول مشاهده، بعد نتیجه‌گیری',why:'هنوز فعالیت کافی ثبت نشده است.',action:'یک مأموریت را همراه کودک انجام بدهید و انتخاب‌ها و سؤال‌هایش را بدون برچسب‌زدن ببینید.'});if(last.some(e=>(e.data.hints||0)>=2))recommendations.push({title:'یک قدم کوچک‌تر',why:'در یکی از سه مأموریت اخیر، حداقل دو راهنما استفاده شده.',action:'پیش از بازی بعد، صورت مسئله را با زبان خود کودک بازگو کنید؛ کمک‌گرفتن شکست نیست.'});if(state.favorites.length)recommendations.push({title:'فرصت بیشتر برای علاقهٔ انتخابی',why:'کودک خودش یک یا چند موضوع را به علاقه‌مندی‌ها افزوده است.',action:'یک تجربهٔ خارج از صفحه در همان موضوع پیشنهاد کنید؛ این نشانهٔ علاقه است، نه تشخیص استعداد ثابت.'});recommendations.push({title:'برنامه را با انرژی امروز تنظیم کن',why:state.energy==='low'?'امروز انرژی کم ثبت شده است.':'تعادل بازی، ارتباط و استراحت مهم است.',action:state.energy==='low'?'فقط یک ارتباط کوتاه و یک عادت ضروری کافی است. باقی برنامه قابل جابه‌جایی است.':'یک بازی مشترک و زمان جداگانه برای هر کودک انتخاب کنید.'});return recommendations;}
