import {test,expect} from '@playwright/test';
import {MISSIONS,SCENARIOS,LESSONS,missionStory} from '../../src/family/content.js';
import {puzzleSpec} from '../../src/family/puzzles.js';
const state=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('hamrah-family-v2')));
async function solve(page,type,m){const s=puzzleSpec(type,m);
 if(['choice','geography'].includes(s.kind))await page.locator(`[data-choice="${s.correct}"]`).click();
 if(s.kind==='route')for(const cell of s.route.slice(1))await page.locator(`[data-cell="${cell}"]`).click();
 if(s.kind==='balance'){for(let i=0;i<Math.floor(s.target/5);i++)await page.locator('[data-weight-add="2"]').click();for(let i=0;i<s.target%5;i++)await page.locator('[data-weight-add="0"]').click();await page.locator('#check-balance').click();}
 if(s.kind==='market'){await page.locator('[data-item="0"]').click();await page.locator('[data-item="2"]').click();await page.locator('#check-items').click();}
 if(s.kind==='multi'){for(let i of s.correct)await page.locator(`[data-item="${i}"]`).click();await page.locator('#check-items').click();}
 if(s.kind==='pixels'){for(let i=0;i<9;i++)if(s.target[i])await page.locator(`[data-pixel="${i}"]`).click();await page.locator('#check-pixels').click();}
 if(s.kind==='code'){for(let i=0;i<3;i++)for(let n=0;n<s.target[i];n++)await page.locator(`[data-digit="${i}"]`).click();await page.locator('#check-code').click();}
 if(s.kind==='order'){for(const word of s.answer)await page.locator(`[data-order="${s.items.indexOf(word)}"]`).click();await page.locator('#check-order').click();}
 if(s.kind==='memory'){for(const symbol of new Set(s.deck))for(let i=0;i<s.deck.length;i++)if(s.deck[i]===symbol)await page.locator(`[data-memory="${i}"]`).click();}
 if(s.kind==='rhythm'){await page.locator('#show-pattern').click();for(const n of s.pattern)await page.locator(`[data-note="${n}"]`).click();}
 await expect(page.locator('#advance-activity')).toBeEnabled();
}
async function completeMission(page,m){await page.locator(`[data-story-choice="${missionStory(m).answer}"]`).click();await page.locator('#advance-activity').click();for(const type of m.puzzles){await solve(page,type,m);await page.locator('#advance-activity').click();}await page.locator('#real-done').check();await page.locator('#advance-activity').click();await page.locator('[data-reflect]').first().click();await page.locator('#advance-activity').click();await expect(page.locator('.reward-bloom')).toBeVisible();}

test('four roles, mobile switching, route locks, voice persistence and no missing assets',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));await page.locator('[data-action=page][data-page=journey]').first().click();await expect(page.locator('.map-node')).toHaveCount(20);await page.locator('.map-node[data-id="2"]').click();await expect(page.locator('#toast')).toContainText('اول مأموریت');await expect(page.locator('.f-modal')).toHaveCount(0);await page.locator('[data-action=page][data-page=voices]').first().click();await page.locator('[data-action=select-voice][data-value=second]').click();await page.reload();expect((await state(page)).voices.explorer).toBe('second');
 await page.setViewportSize({width:390,height:844});for(const role of ['toddler','mother','father','explorer']){await page.locator('.top-avatar').click();await page.locator(`.profile-roles [data-role=${role}]`).click();expect((await state(page)).role).toBe(role);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}expect(errors).toEqual([]);
});
test('checkpoint resumes, replay earns no duplicate reward, recording is optional and consent-gated',async({page})=>{
 await page.goto('/');await page.locator('.journey-hero [data-action=mission]').click();await page.locator('[data-story-choice="0"]').click();await page.locator('#advance-activity').click();await page.locator('#close-modal').click();await page.reload();await page.locator('.journey-hero [data-action=mission]').click();await expect(page.locator('.route-grid')).toBeVisible();for(const type of MISSIONS[0].puzzles){await solve(page,type,MISSIONS[0]);await page.locator('#advance-activity').click();}await page.locator('#real-done').check();await page.locator('#advance-activity').click();await page.locator('#record-start').click();await expect(page.locator('#record-status')).toContainText('اجازه');await page.locator('[data-reflect]').first().click();await page.locator('#advance-activity').click();expect((await state(page)).events.filter(e=>e.kind==='mission')).toHaveLength(1);
 await page.locator('#close-modal').click();await page.locator('[data-action=page][data-page=journey]').first().click();await page.locator('.map-node[data-id="1"]').click();await completeMission(page,MISSIONS[0]);expect((await state(page)).events.filter(e=>e.kind==='mission')).toHaveLength(1);
});
test('all twelve toddler sessions finish through observation, without speech or scoring',async({page})=>{
 await page.goto('/?edition=toddler');for(let id=1;id<=12;id++){await page.locator(`[data-action=toddler][data-id="${id}"]`).click();await page.locator('[data-action=toddler-begin]').click();await page.locator('#just-look').click();await page.locator('#advance-activity').click();await page.locator('#toddler-turn').click();await page.locator('#advance-activity').click();await page.locator('[data-observation]').last().click();await page.locator('#advance-activity').click();await page.locator('#close-modal').click();}const s=await state(page);expect(s.events.filter(e=>e.kind==='toddler')).toHaveLength(12);expect(s.events.every(e=>e.data.score===undefined)).toBe(true);
});
test('all fifteen parenting lessons, routine tracking and father cycle settings',async({page})=>{
 await page.goto('/?edition=mother');await page.locator('[data-action=page][data-page=journey]').first().click();for(const l of LESSONS){await page.locator(`[data-action=lesson][data-id="${l.id}"]`).click();await page.locator('[data-parent-choice="0"]').click();await page.locator('#advance-activity').click();await page.locator('#practice-sentence').check();await page.locator('#advance-activity').click();await page.locator('[data-parent-reflect]').first().click();await page.locator('#advance-activity').click();await page.locator('#close-modal').click();}expect((await state(page)).events.filter(e=>e.kind==='lesson')).toHaveLength(15);
 await page.locator('[data-action=page][data-page=home]').first().click();await page.locator('[data-action=energy][data-value=low]').click();await expect(page.locator('.routine-item')).toHaveCount(3);await page.locator('.routine-item').first().click();await page.locator('.routine-item').first().click();expect((await state(page)).events.filter(e=>e.kind==='routine')).toHaveLength(1);
 await page.goto('/?edition=father');await expect(page.locator('.cycle-strip span')).toHaveCount(15);await page.locator('.top-avatar').click();await page.locator('.f-modal [data-page=settings]').click();await page.locator('input[name=cycle]').fill('2026-09-01');await page.locator('#settings-form button').click();expect((await state(page)).cycleStart).toBe('2026-09-01');
});
test('family backup export/import and shared game registration',async({page})=>{
 await page.goto('/?edition=mother');await page.locator('[data-action=page][data-page=together]').first().click();await page.locator('[data-action=together][data-id="1"]').click();await page.locator('#together-done').check();await page.locator('#save-together').click();await page.locator('.top-avatar').click();await page.locator('.f-modal [data-page=settings]').click();const download=page.waitForEvent('download');await page.locator('[data-action=export]').click();expect((await download).suggestedFilename()).toBe('bagh-family-backup.json');const s=await state(page);await page.locator('#import-backup').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(s))});expect((await state(page)).events.filter(e=>e.kind==='together')).toHaveLength(1);
});
for(let chapter=0;chapter<10;chapter++)test(`v2 chapter ${chapter+1}: all twenty missions and one hundred stations`,async({page})=>{
 test.setTimeout(180000);await page.goto('/');await page.evaluate(chapter=>localStorage.setItem('hamrah-family-v2',JSON.stringify({version:2,role:'explorer',limit:30,events:Array.from({length:chapter*20},(_,i)=>({id:'seed-'+i,role:'explorer',kind:'mission',subject:String(i+1),at:Date.now()-1000,data:{}}))})),chapter);await page.reload();await page.locator('.journey-hero [data-action=mission]').click();for(const m of MISSIONS.filter(m=>m.chapter===chapter)){await completeMission(page,m);if(m.local<20)await page.locator('[data-action=next-mission]').click();}expect((await state(page)).events.filter(e=>e.kind==='mission')).toHaveLength((chapter+1)*20);
});
